model:
  vit:
    in_channels: 1
    embedding_dim: 192
    patch_size: 16
    max_patch_num: 4096
    depth: 6
    n_heads: 8
    mlp_size: 768
  cls:
    n_classes: 4

model_weights:
  vit_backbone: "model_weights/vit_backbone.pth"
  classifier: "model_weights/classifier.pth"
  
training:
  num_epochs: 90
  warmup_epochs: 10
  batch_size: 1024
  lr: 3e-4
  use_amp: True
  device: "cuda"

